#Updated: 2026-04-05T21:21:06.407937100Z
#Sun Apr 05 16:21:06 GMT-05:00 2026
background_path=C\:\\Users\\diego\\OneDrive\\Documentos\\04_Projects_Dev\\NetBeansProjects\\Reloj_Clock\\src\\resources\\wallpaper\\1359472.png
clock_color=0,0,255
clock_position=LEFT
font_name=Algerian
font_size=41
font_style=2
recent_colors=0,0,0;255,255,255;255,215,0;70,130,180;
wallpapers=10101.png,10102.png,10103.png,10104.png
